version: '3'

env:
  GOOS: "{{OS}}"
  
vars:
  APPNAME: http-server
  EXEFILE: http-server{{exeExt}}


includes:
  build: ./BuildTaskfile.yml

tasks:
  build:
    cmds:
      - task: build:default

  clean:
    cmds:
      - go clean

  run:
    deps: [build]
    cmds:
      - ./{{.EXEFILE}}
    ignore_error: true

  release:
    deps: [clean]
    cmds:
      - task: build:x64
      - 7z a -tzip ./release/{{.APPNAME}}_{{.GOOS}}_amd64_{{.GIT_COMMIT}}.zip {{.EXEFILE}}
      - task: clean
      - task: build:x86
      - 7z a -tzip ./release/{{.APPNAME}}_{{.GOOS}}_386_{{.GIT_COMMIT}}.zip {{.EXEFILE}}
      - task: clean
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
